import type { HelpHintContent } from "@/modules/explanations/types";

const helpHints: Record<string, HelpHintContent> = {
  forma_juridica: {
    key: "forma_juridica",
    title: "Forma juridica",
    shortLabel: "Define el tipo societario base.",
    whatIsIt: "Es la figura legal con la que opera la organizacion, como SA, SRL, SAS o unipersonal.",
    whyItMatters: "Ayuda a materializar el perfil fiscal inicial y a presentar reportes con el contexto correcto.",
    impact: "Afecta snapshots, validaciones y explicaciones del sistema, aunque no te obliga a un plan contable cerrado.",
    whatCanYouDo: "Si cambia mas adelante, puedes crear una nueva version del perfil desde configuracion sin reescribir historicos.",
    sourceLabel: "Practica registral y fiscal Uruguay.",
  },
  regimen_tributario: {
    key: "regimen_tributario",
    title: "Regimen tributario",
    shortLabel: "Ubica el marco fiscal principal.",
    whatIsIt: "Es el regimen bajo el cual tributa la organizacion ante DGI.",
    whyItMatters: "El sistema lo usa para resumir reglas, validar snapshots y explicar por que ciertas decisiones requieren revision.",
    impact: "Puede cambiar recomendaciones fiscales, comentarios y controles posteriores.",
    whatCanYouDo: "Si no estas seguro, elige la opcion vigente hoy y corrigela despues desde configuracion.",
    sourceLabel: "Alta registral Uruguay.",
  },
  regimen_iva: {
    key: "regimen_iva",
    title: "Regimen IVA",
    shortLabel: "Define el tratamiento general del IVA.",
    whatIsIt: "Describe el marco principal de IVA con el que opera la organizacion.",
    whyItMatters: "Afecta credito fiscal, explicaciones de IVA y los bloqueos o advertencias del flujo documental.",
    impact: "Cambia snapshots, validaciones y recomendaciones de cuentas relacionadas a IVA.",
    whatCanYouDo: "Si tu operativa cambia, versiona el perfil desde configuracion para que rija hacia adelante.",
    sourceLabel: "DGI Uruguay.",
  },
  grupo_dgi: {
    key: "grupo_dgi",
    title: "Grupo DGI",
    shortLabel: "Ubica el encuadre operativo frente a DGI.",
    whatIsIt: "Es la categoria operativa con la que la organizacion se presenta ante DGI.",
    whyItMatters: "Ayuda a explicar controles, formularios y expectativas de operativa fiscal.",
    impact: "Puede modificar alertas, copy y criterios de seguimiento en impuestos.",
    whatCanYouDo: "Corrigelo despues si necesitas reflejar una realidad registral distinta.",
    sourceLabel: "Formulario 0351 y practica DGI.",
  },
  estado_cfe: {
    key: "estado_cfe",
    title: "Estado CFE",
    shortLabel: "Aclara si la empresa emite electronicamente.",
    whatIsIt: "Indica si la organizacion es emisora electronica, receptora o aun no opera con CFE.",
    whyItMatters: "Sirve para contextualizar la operativa documental y ciertas expectativas del flujo.",
    impact: "No bloquea empezar, pero mejora la explicacion del contexto fiscal y documental.",
    whatCanYouDo: "Actualizalo cuando la situacion cambie, sin tocar historicos cerrados.",
    sourceLabel: "Operativa CFE Uruguay.",
  },
  actividad_principal: {
    key: "actividad_principal",
    title: "Actividad principal",
    shortLabel: "Es el mejor resumen del negocio principal.",
    whatIsIt: "Es la actividad economica CIIU que mejor representa la operativa principal de la empresa.",
    whyItMatters: "Es el insumo mas fuerte para recomendar overlays del plan de cuentas y templates iniciales.",
    impact: "Cambia la recomendacion del plan, las capacidades sugeridas y parte del lenguaje explicativo.",
    whatCanYouDo: "Puedes corregirla o reemplazarla despues desde configuracion si el negocio evoluciona.",
    sourceLabel: "DGI CIIU Rev.4.",
  },
  actividades_secundarias: {
    key: "actividades_secundarias",
    title: "Actividades secundarias",
    shortLabel: "Complementan el negocio principal.",
    whatIsIt: "Son actividades relevantes que no son el foco principal, pero agregan operativa real.",
    whyItMatters: "Permiten sumar overlays sin inventar un plan distinto por cada empresa.",
    impact: "Pueden agregar cuentas o templates especializados sin tocar la base general.",
    whatCanYouDo: "Marca solo las que sean recurrentes o materialmente relevantes para no sobredimensionar el plan.",
    sourceLabel: "Criterio registral y operativo.",
  },
  rasgos_operativos: {
    key: "rasgos_operativos",
    title: "Rasgos operativos y fiscales",
    shortLabel: "Explican como opera la empresa en la practica.",
    whatIsIt: "Son banderas que describen si importa, exporta, usa varias monedas, mezcla IVA, trabaja por contratos y otros rasgos clave.",
    whyItMatters: "Ajustan la recomendacion sin obligarte a elegir un plan completamente distinto por rubro.",
    impact: "Pueden agregar overlays, comentarios y controles especificos de IVA o contabilidad.",
    whatCanYouDo: "Si un rasgo aun es eventual, dejalo apagado y activalo cuando la operativa sea real.",
    sourceLabel: "Practica fiscal y operativa Uruguay.",
  },
  descripcion_negocio: {
    key: "descripcion_negocio",
    title: "Descripcion corta del negocio",
    shortLabel: "Ayuda a desempatar, no decide sola.",
    whatIsIt: "Es una frase breve donde explicas en lenguaje humano a que se dedica la empresa.",
    whyItMatters: "Sirve para sugerir actividades y mejorar el comentario del plan recomendado cuando el catalogo queda corto.",
    impact: "Nunca autoaplica un preset por si sola; solo afina sugerencias.",
    whatCanYouDo: "Usa una frase corta y concreta. Si no quieres completarla, puedes seguir igual.",
    sourceLabel: "Heuristica local del sistema.",
  },
  plan_recomendado: {
    key: "plan_recomendado",
    title: "Plan recomendado",
    shortLabel: "Es una composicion de base + overlays.",
    whatIsIt: "Es una propuesta armada con un plan base Uruguay y capas adicionales segun actividad y rasgos.",
    whyItMatters: "Te permite empezar con una estructura razonable sin tener que inventarla desde cero.",
    impact: "Puede agregar cuentas, templates y hints pensados para tu operativa probable.",
    whatCanYouDo: "Puedes aceptarlo, elegir una alternativa, importar tu plan o empezar con minimo + temporales.",
    sourceLabel: "Composicion interna versionada en el repo.",
  },
  importar_plan_externo: {
    key: "importar_plan_externo",
    title: "Importar plan externo",
    shortLabel: "Te deja entrar con tu estructura actual.",
    whatIsIt: "Es la opcion para traer un plan de cuentas desde una planilla o layout externo.",
    whyItMatters: "Evita que el onboarding sea un callejon sin salida para contadores que ya tienen su plan.",
    impact: "La organizacion puede empezar operando igual con starter + temporales mientras completas la importacion.",
    whatCanYouDo: "Si la importacion falla, puedes seguir con minimo + temporales y volver a intentarlo despues.",
    sourceLabel: "Workspace de importaciones Convertilabs.",
  },
  minimo_temporales: {
    key: "minimo_temporales",
    title: "Minimo + temporales",
    shortLabel: "Permite empezar sin definir todo hoy.",
    whatIsIt: "Es una base operable con cuentas tecnicas y cuentas TEMP-* para los casos donde todavia no definiste el plan final.",
    whyItMatters: "Destraba el onboarding y el pipeline documental sin forzar una decision contable perfecta desde el primer dia.",
    impact: "Los documentos se procesan igual, pero algunos caeran en recategorizacion o aprendizaje posterior.",
    whatCanYouDo: "Puedes completar el plan despues, importar uno externo o aplicar una composicion recomendada mas adelante.",
    sourceLabel: "Fallback operativo del sistema.",
  },
  cuenta_temporal: {
    key: "cuenta_temporal",
    title: "Cuenta temporal",
    shortLabel: "Se usa cuando aun falta una cuenta definitiva.",
    whatIsIt: "Es una cuenta TEMP-* creada para no bloquear el procesamiento mientras todavia no se definio una cuenta final.",
    whyItMatters: "Permite postear provisionalmente y seguir trabajando sin perder trazabilidad.",
    impact: "Requiere recategorizacion posterior si quieres dejar el asiento final mas fino.",
    whatCanYouDo: "Puedes crear la cuenta definitiva desde revision o desde organizacion y volver a clasificar hacia adelante.",
    sourceLabel: "Fallback contable controlado.",
  },
  posteo_provisional: {
    key: "posteo_provisional",
    title: "Posteo provisional",
    shortLabel: "Permite avanzar sin cerrar todo en forma definitiva.",
    whatIsIt: "Es un estado donde el documento ya impacta operativamente, pero aun puede necesitar recategorizacion o ajuste final.",
    whyItMatters: "Ayuda a no detener el flujo por ambiguedades menores o cuentas aun no cerradas.",
    impact: "El documento puede alimentar algunos procesos, pero sigue marcado para seguimiento.",
    whatCanYouDo: "Puedes confirmar final mas adelante cuando la cuenta o el criterio queden cerrados.",
    sourceLabel: "Lifecycle documental contable.",
  },
  iva_directo: {
    key: "iva_directo",
    title: "IVA directo",
    shortLabel: "Credito vinculado directamente al giro gravado.",
    whatIsIt: "Es la parte del IVA compras que se puede vincular de forma directa con operaciones gravadas.",
    whyItMatters: "Suele ser la porcion mas fuerte del credito fiscal y por eso debe quedar bien explicada.",
    impact: "Afecta el credito fiscal usable del periodo.",
    whatCanYouDo: "Si no coincide con tu criterio, revisa categoria operativa, contexto contable o regla aplicada.",
    sourceLabel: "Criterio IVA Uruguay.",
  },
  iva_indirecto: {
    key: "iva_indirecto",
    title: "IVA indirecto",
    shortLabel: "Credito que puede requerir prorrata o revision.",
    whatIsIt: "Es la parte del IVA compras vinculada indirectamente al negocio o a operativa mixta.",
    whyItMatters: "Puede requerir prorrata o tratamiento mas conservador antes de confirmar.",
    impact: "Puede mover montos entre deducible, no deducible o revision manual.",
    whatCanYouDo: "Si tienes fundamento para otro criterio, agrega contexto y revisa el tratamiento final.",
    sourceLabel: "DGI Uruguay - prorrata y mixtos.",
  },
  iva_no_deducible: {
    key: "iva_no_deducible",
    title: "IVA no deducible",
    shortLabel: "Es IVA que no se toma como credito fiscal.",
    whatIsIt: "Es la porcion del IVA compras que el sistema no considera acreditable para este documento.",
    whyItMatters: "Impacta directamente el resultado fiscal del periodo.",
    impact: "Se mueve fuera del credito deducible y puede pasar a gasto u otro tratamiento.",
    whatCanYouDo: "Si no estas de acuerdo, revisa la categoria, el nexo con giro y la evidencia del caso.",
    sourceLabel: "Criterio IVA Uruguay.",
  },
  razonabilidad_geografica: {
    key: "razonabilidad_geografica",
    title: "Razonabilidad geografica",
    shortLabel: "Chequea si el gasto tiene sentido con la base operativa.",
    whatIsIt: "Es una senal que compara el lugar del gasto con la base geografica conocida de la organizacion.",
    whyItMatters: "Ayuda a detectar gastos sensibles que pueden necesitar evidencia adicional de proposito empresarial.",
    impact: "Puede exigir nota auditada, sugerir revision manual o endurecer la confirmacion final.",
    whatCanYouDo: "Explica el viaje, cliente, obra o actividad que justifica el gasto y deja evidencia contextual.",
    sourceLabel: "Politica geografica local del sistema.",
  },
  tipo_cambio_fiscal: {
    key: "tipo_cambio_fiscal",
    title: "Tipo de cambio fiscal usado",
    shortLabel: "Muestra con que criterio se paso a UYU.",
    whatIsIt: "Es la regla y el valor usados para convertir la moneda original a UYU con trazabilidad.",
    whyItMatters: "Sin esta trazabilidad, IVA y contabilidad en moneda funcional quedan opacos.",
    impact: "Afecta montos UYU, IVA, journal y exportaciones posteriores.",
    whatCanYouDo: "Si corresponde un override documentado, debe quedar con razon explicitada y trazable.",
    sourceLabel: "DGI / criterio BCU persistido.",
  }
};

export const onboardingHelpHintKeys = [
  "forma_juridica",
  "regimen_tributario",
  "regimen_iva",
  "grupo_dgi",
  "estado_cfe",
  "actividad_principal",
  "actividades_secundarias",
  "rasgos_operativos",
  "descripcion_negocio",
  "plan_recomendado",
  "importar_plan_externo",
  "minimo_temporales",
] as const;

export const reviewHelpHintKeys = [
  "cuenta_temporal",
  "posteo_provisional",
  "iva_directo",
  "iva_indirecto",
  "iva_no_deducible",
  "razonabilidad_geografica",
  "tipo_cambio_fiscal",
] as const;

export function getHelpHintContent(key: string) {
  return helpHints[key] ?? null;
}

export function listHelpHintKeys() {
  return Object.keys(helpHints).sort();
}
