/* eslint-disable @typescript-eslint/no-require-imports */
const { test, assert } = require("./testkit.cjs");

const {
  buildAccountingDecisionLog,
  buildDocumentIntakeDecisionLog,
  resolveCertaintyLevel,
} = require("@/modules/accounting/decision-log");

test("certainty level uses green yellow red thresholds", () => {
  assert.equal(resolveCertaintyLevel({ confidence: 0.95, warnings: [], blockers: [] }), "green");
  assert.equal(resolveCertaintyLevel({ confidence: 0.8, warnings: ["warning"], blockers: [] }), "yellow");
  assert.equal(resolveCertaintyLevel({ confidence: 0.4, warnings: [], blockers: [] }), "red");
});

test("document intake decision log marks deterministic organization identity as deterministic_rule", () => {
  const result = buildDocumentIntakeDecisionLog({
    organizationId: "org-1",
    documentId: "doc-1",
    providerCode: "openai",
    modelCode: "gpt-4o",
    promptVersion: "2026-03-14",
    schemaVersion: "2026-03-14",
    responseId: "resp-1",
    structuredOutput: {
      extracted_text: "Factura",
      confidence_score: 0.94,
      warnings: [],
      transaction_family_candidate: "sale",
      document_subtype_candidate: "sale_invoice",
      issuer_matches_organization: {
        status: "matched",
        strategy: "tax_id",
        matched_alias: null,
        normalized_tax_id: "21433455019",
        normalized_name: null,
        confidence: 1,
        evidence: ["RUT"],
      },
      receiver_matches_organization: {
        status: "not_matched",
        strategy: "none",
        matched_alias: null,
        normalized_tax_id: null,
        normalized_name: null,
        confidence: 0,
        evidence: [],
      },
      certainty_breakdown_json: {
        extraction_confidence: 0.94,
        organization_identity_confidence: 1,
        line_items_confidence: 0.9,
        warning_count: 0,
        warning_flags: [],
      },
      document_role_candidate: "sale",
      document_type_candidate: "sale_invoice",
      operation_category_candidate: "taxed_basic_22",
      facts: {
        issuer_name: "Rontil",
        issuer_tax_id: "21433455019",
        receiver_name: "Cliente",
        receiver_tax_id: "21999999999",
        document_number: "123",
        series: "A",
        currency_code: "UYU",
        document_date: "2026-03-14",
        due_date: null,
        subtotal: 100,
        tax_amount: 22,
        total_amount: 122,
        purchase_category_candidate: null,
        sale_category_candidate: "taxed_basic_22",
      },
      amount_breakdown: [],
      line_items: [],
      explanations: {
        classification: "Venta",
        facts: "Factura",
      },
    },
    transactionFamilyResolution: {
      documentRole: "sale",
      documentSubtype: "sale_invoice",
      source: "deterministic_tax_id",
      confidence: 1,
      shouldReview: false,
      warnings: [],
      evidence: ["issuer"],
    },
  });

  assert.equal(result.decision_source, "deterministic_rule");
  assert.equal(result.certainty_level, "green");
});

test("accounting decision log surfaces manual overrides and rule metadata", () => {
  const result = buildAccountingDecisionLog({
    organizationId: "org-1",
    documentId: "doc-1",
    providerCode: null,
    modelCode: null,
    derived: {
      taxTreatment: {
        ready: true,
        treatmentCode: "vat_purchase_creditable",
        label: "IVA compras acreditable",
        vatBucket: "input_creditable",
        taxableAmount: 100,
        taxAmount: 22,
        rate: 22,
        explanation: "ok",
        warnings: [],
        blockingReasons: [],
        normativeSummary: "snapshot",
        deterministicRuleRefs: [],
        requiresManualReview: false,
        journalSeed: null,
      },
      journalSuggestion: {
        ready: true,
        isBalanced: true,
        totalDebit: 122,
        totalCredit: 122,
        functionalTotalDebit: 122,
        functionalTotalCredit: 122,
        currencyCode: "UYU",
        functionalCurrencyCode: "UYU",
        fxRate: 1,
        fxRateDate: "2026-03-14",
        fxRateSource: "same_currency",
        explanation: "Manual override",
        lines: [],
        blockingReasons: [],
      },
      vendorResolution: {
        status: "matched",
        matchStrategy: "tax_id",
        vendorId: "vendor-1",
        vendorName: "Proveedor",
        normalizedTaxId: "21433455019",
        normalizedName: "proveedor",
        defaultAccountId: null,
        defaultPaymentAccountId: null,
        defaultTaxProfile: null,
        defaultOperationCategory: null,
        candidates: [],
        blockingReasons: [],
      },
      invoiceIdentity: {
        issuerTaxIdNormalized: "21433455019",
        issuerNameNormalized: "proveedor",
        documentNumberNormalized: "a123",
        documentDate: "2026-03-14",
        totalAmount: 122,
        currencyCode: "UYU",
        identityStrategy: "tax_id_number_date",
        invoiceIdentityKey: "21433455019|a123|2026-03-14",
        duplicateStatus: "clear",
        duplicateOfDocumentId: null,
        duplicateReason: null,
        shouldBlockConfirmation: false,
        blockingReasons: [],
      },
      conceptResolution: {
        lines: [],
        fallbackUsed: false,
        primaryConceptLabels: [],
        matchedConceptIds: [],
        blockingReasons: [],
        needsUserContext: false,
        unresolvedLineCount: 0,
      },
      accountingContext: {
        status: "manual_override",
        reasonCodes: [],
        userFreeText: null,
        structuredContext: {},
        aiRequestPayload: {},
        aiResponse: {},
        providerCode: null,
        modelCode: null,
        promptHash: null,
        requestLatencyMs: null,
        manualOverrideAccountId: "acct-1",
        manualOverrideConceptId: null,
        manualOverrideOperationCategory: "services",
        learnedConceptName: null,
        shouldBlockConfirmation: false,
        canRunAssistant: false,
        blockingReasons: [],
      },
      assistantSuggestion: {
        status: "not_requested",
        shouldBlockConfirmation: false,
        confidence: null,
        rationale: null,
        output: null,
        providerCode: null,
        modelCode: null,
        promptHash: null,
        latencyMs: null,
        requestPayload: {},
        responsePayload: {},
        reviewFlags: [],
      },
      appliedRule: {
        ruleId: "rule-1",
        scope: "document_override",
        accountId: "acct-1",
        accountCode: "6101",
        accountName: "Gastos",
        vatProfileJson: null,
        operationCategory: "services",
        linkedOperationType: null,
        provenance: "manual_override",
        priority: 1000,
        source: "manual",
        createdAt: "2026-03-14T10:00:00Z",
      },
      validation: {
        canConfirm: true,
        blockers: [],
      },
    },
  });

  assert.equal(result.decision_source, "manual_override");
  assert.equal(result.metadata_json.rule_created_at, "2026-03-14T10:00:00Z");
});
